# ===== fmcsa-dispatcher.yml (Updated) =====
name: FMCSA Dispatcher (All Batches)

on:
  workflow_dispatch:
    inputs:
      batch_size:
        description: 'Batch size per run'
        required: false
        default: '250'
      concurrency:
        description: 'Parallel requests per extractor'
        required: false
        default: '8'
      delay:
        description: 'Delay between waves (ms)'
        required: false
        default: '1000'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Split mc_list into batches
        run: |
          mkdir -p batches
          split -l ${{ github.event.inputs.batch_size }} mc_list.txt batches/batch_

      - name: Dispatch extractor for each batch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          i=0
          for f in batches/*; do
            echo "Dispatching batch $f (index $i)..."
            gh workflow run extractor.yml \
              --ref main \
              -f batch_index=$i \
              -f batch_size=${{ github.event.inputs.batch_size }} \
              -f concurrency=${{ github.event.inputs.concurrency }} \
              -f delay=${{ github.event.inputs.delay }}
            i=$((i+1))
            sleep 2
          done

  gatekeeper:
    runs-on: ubuntu-latest
    needs: dispatch
    steps:
      - uses: actions/checkout@v4

      # === YAHAN ACTION BADLA GAYA HAI ===
      - name: Wait for all dispatched workflows to complete
        uses: lewagon/wait-on-check-action@v1.3.3
        with:
          ref: ${{ github.ref }}
          check-name: 'run' # 'run' job ka naam hai extractor.yml mein
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 60 # Har 60 seconds mein check karo
          running-workflow-name: 'FMCSA Extractor (Single Batch)' # Is workflow ke saare runs ka intezar karo

      - name: All batches complete, triggering merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "✅ All extractor jobs are done. Triggering the merge process."
          gh workflow run "FMCSA Post Merge" --ref main
