# ===== fmcsa-dispatcher.yml (Corrected) =====
name: FMCSA Dispatcher (All Batches)

on:
  workflow_dispatch:
    inputs:
      batch_size:
        description: 'Batch size per run'
        required: false
        default: '250'
      concurrency:
        description: 'Parallel requests per extractor'
        required: false
        default: '8'
      delay:
        description: 'Delay between waves (ms)'
        required: false
        default: '1000'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Split mc_list into batches
        id: split
        run: |
          mkdir -p batches
          split -l ${{ github.event.inputs.batch_size }} mc_list.txt batches/batch_
          B_COUNT=$(ls batches | wc -l)
          echo "batch_count=$B_COUNT" >> $GITHUB_OUTPUT
          echo "✅ Created $B_COUNT batches."

      - name: Dispatch extractor for each batch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          i=0
          for f in batches/*; do
            echo "Dispatching batch $f (index $i)..."
            gh workflow run extractor.yml \
              --ref main \
              -f batch_index=$i \
              -f batch_size=${{ github.event.inputs.batch_size }} \
              -f concurrency=${{ github.event.inputs.concurrency }} \
              -f delay=${{ github.event.inputs.delay }}
            i=$((i+1))
            sleep 2 # API rate limit se bachne ke liye thora pause
          done

  # Yeh job saare batches ke complete hone ka intezar karega
  gatekeeper:
    runs-on: ubuntu-latest
    needs: dispatch # Pehle dispatch job chalega
    steps:
      # YEH STEP ADD KIYA GAYA HAI (THE FIX)
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Wait for all dispatched workflows to complete
        uses: ahmadnassri/action-workflow-run-wait@v1
        with:
          workflow: extractor.yml # Intezar karo 'extractor.yml' ke saare runs ka
          token: ${{ secrets.GITHUB_TOKEN }}
          timeout: 3600000 # 1 ghanta timeout
          retries: 5
          wait: 60000 # Har 1 minute baad check karo

      - name: All batches complete, triggering merge
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "✅ All extractor jobs are done. Triggering the merge process."
          gh workflow run fmcsa-post-merge.yml --ref main
